# shopify.app.toml
name = "traffic-takip"
client_id = "b1ff4db0087606d8bacc80ca886d15f6"
application_url = "https://traffic-takip-production.up.railway.app"
embedded = true

[auth]
redirect_urls = ["https://traffic-takip-production.up.railway.app/auth/callback"]

[app_proxy]
prefix = "apps"
subpath = "app-proxy"
url = "https://traffic-takip-production.up.railway.app/app-proxy"

[webhooks]
api_version = "2025-07"
