# Theme App Extension Configuration
# Bu dosya Theme App Extension'ın temel konfigürasyonunu içerir

api_version = "2023-10"

[[extensions]]
type = "theme"
name = "HRL Traffic Tracking"

# Otomatik enjeksiyon ayarları
[extensions.targeting]
target = "head"

[extensions.settings]